In [1]:
import cv2
import numpy as np

In [15]:
mser = cv2.MSER_create()

#Your image path i-e receipt path
img = cv2.imread("bookpage.jpg")

#Convert to gray scale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

vis = img.copy()

#detect regions in gray scale image
regions, _ = mser.detectRegions(gray)

hulls = [cv2.convexHull(p.reshape(-1, 1, 2)) for p in regions]

# len(hulls[1][0])
# cv2.polylines(vis, hulls, 1, (0, 255, 0))
pts = np.array([[10,5],[20,30],[70,20],[50,10]], np.int32)

a = np.array(hulls[0])


print(pts)
print(a)


cv2.polylines(vis, [a], 1, (0, 255, 0))

cv2.imshow('img', vis)

# cv2.waitKey(1)

# mask = np.zeros((img.shape[0], img.shape[1], 1), dtype=np.uint8)

# for contour in hulls:

#     cv2.drawContours(mask, [contour], -1, (255, 255, 255), -1)

# #this is used to find only text regions, remaining are ignored
# text_only = cv2.bitwise_and(img, img, mask=mask)

# cv2.imshow("text only", text_only)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[10  5]
 [20 30]
 [70 20]
 [50 10]]
[[[ 25 116]]

 [[ 24 118]]

 [[ 21 121]]

 [[ 18 122]]

 [[ 10 122]]

 [[ 10  81]]

 [[ 20  81]]

 [[ 22  82]]

 [[ 23  83]]

 [[ 25  87]]]
